<a href="https://colab.research.google.com/github/thecodingAdi/ai-ml-playground/blob/main/GridSearch_CV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<!-- Cleaned: GitHub Credentials section -->

In [128]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [129]:
df = sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [130]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [131]:
from sklearn.model_selection import train_test_split

In [132]:
X = df.drop('species', axis=1)
y = df['species']

In [133]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

<!-- Cleaned: Clone Repository section -->

In [134]:
from sklearn.neighbors import KNeighborsClassifier

In [135]:
model_knn = KNeighborsClassifier(n_neighbors=5)

<!-- Cleaned: Add Changes and Push section -->

In [136]:
model_knn.fit(X_train, y_train)

KNeighborsClassifier()

<!-- Cleaned: Save and Push specific files section -->

In [137]:
model_knn.score(X_test, y_test)

0.98

In [138]:
from sklearn.svm import SVC

In [139]:
model_svm = SVC(C=30, gamma='auto', kernel= 'rbf')

<!-- Cleaned: Create and Push a New Working File section -->

In [140]:
model_svm.fit(X_train, y_train)

SVC(C=30, gamma='auto')

<!-- Cleaned: Push to GitHub instructions -->

In [141]:
model_svm.score(X_test, y_test)

0.98

In [142]:
 # Using Grid Search CV

In [143]:
from sklearn.model_selection import GridSearchCV

In [144]:
classifier = GridSearchCV((model_svm),{
    'C' : [1,10,20,30],
    'kernel' : ['rbf', 'linear']
}, cv=5, return_train_score=False)

In [145]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(C=30, gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [146]:
classifier.cv_results_

{'mean_fit_time': array([0.00236993, 0.00211325, 0.00205517, 0.0019536 , 0.00205274,
        0.00194016, 0.00205359, 0.0019825 ]),
 'std_fit_time': array([3.38803972e-04, 2.11536142e-04, 4.28140292e-05, 2.95977245e-05,
        3.68322059e-05, 1.45951122e-05, 4.17093799e-05, 3.01817205e-05]),
 'mean_score_time': array([0.0018065 , 0.00160418, 0.00157633, 0.00158749, 0.00154924,
        0.00151539, 0.00154762, 0.00152459]),
 'std_score_time': array([2.95367655e-04, 8.57977804e-05, 4.30662363e-05, 6.41207875e-05,
        1.66545233e-05, 1.77720222e-05, 1.74716414e-05, 2.75447658e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [147]:
result = pd.DataFrame(classifier.cv_results_)

In [148]:
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002370,0.000339,0.001806,0.000295,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002113,0.000212,0.001604,0.000086,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.002055,0.000043,0.001576,0.000043,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.001954,0.000030,0.001587,0.000064,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.002053,0.000037,0.001549,0.000017,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.001940,0.000015,0.001515,0.000018,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.002054,0.000042,0.001548,0.000017,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.001982,0.000030,0.001525,0.000028,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [149]:
result[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [150]:
classifier2 = GridSearchCV((model_knn),{
    'n_neighbors' : [1,5,10],
    'algorithm' : ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'metric' : ['minkowski', 'euclidean', 'manhattan'],
    'weights' : ['uniform', 'distance']
}, cv=5, return_train_score=False)

In [152]:
classifier2.fit(X,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'metric': ['minkowski', 'euclidean', 'manhattan'],
                         'n_neighbors': [1, 5, 10],
                         'weights': ['uniform', 'distance']})

In [153]:
classifier2.cv_results_

{'mean_fit_time': array([0.00373673, 0.004671  , 0.00481849, 0.00294118, 0.0030705 ,
        0.00309172, 0.0035295 , 0.00311584, 0.00314698, 0.00336003,
        0.00318284, 0.00311842, 0.00330591, 0.00329857, 0.00331726,
        0.00298333, 0.00307021, 0.00325799, 0.00312343, 0.00332079,
        0.00305786, 0.00356922, 0.003052  , 0.00316839, 0.00400648,
        0.00397439, 0.0030448 , 0.00308299, 0.0047143 , 0.0032002 ,
        0.00303984, 0.00316367, 0.00299497, 0.00323091, 0.00310459,
        0.00321045, 0.0030417 , 0.00355654, 0.00310388, 0.00308576,
        0.00296507, 0.00306287, 0.00305324, 0.00310416, 0.00295253,
        0.00302405, 0.00298724, 0.00327649, 0.00296416, 0.00283556,
        0.00304651, 0.00303564, 0.00299339, 0.00297508, 0.00582209,
        0.00325217, 0.00287409, 0.00312638, 0.00447636, 0.00317783,
        0.00290928, 0.00295382, 0.00293722, 0.00587406, 0.0027359 ,
        0.00283689, 0.00315185, 0.00286589, 0.00282369, 0.00279665,
        0.00287037, 0.0030262 ]),
 'std_fit_time': array([8.94149789e-04, 1.41289065e-03, 3.50371416e-03, 1.70885784e-04,
        9.73402766e-05, 8.27772826e-05, 9.10339713e-04, 6.96403325e-05,
        6.30981155e-05, 4.82970442e-04, 1.17663605e-04, 2.80860187e-04,
        3.89270739e-04, 4.47701984e-04, 4.82731334e-04, 2.15846227e-04,
        1.31727937e-05, 2.90550697e-04, 9.17502845e-05, 4.19974245e-04,
        3.09968361e-05, 1.25494999e-03, 2.08536542e-05, 2.41598354e-04,
        1.78211436e-03, 1.72758150e-03, 3.61496033e-05, 1.11042669e-05,
        1.81983103e-03, 8.12769740e-05, 2.01354844e-04, 6.78831917e-05,
        2.27856595e-04, 3.15029267e-04, 2.86928201e-04, 4.54114735e-05,
        1.14879008e-04, 4.99048448e-04, 5.71366730e-05, 3.41275522e-05,
        1.67388222e-04, 5.52928822e-05, 6.90109404e-05, 2.82215096e-05,
        1.86482557e-04, 7.04368381e-05, 2.30826698e-04, 5.21078008e-04,
        2.32795202e-05, 1.17633842e-04, 1.32786521e-04, 1.62632931e-05,
        7.35020003e-05, 1.94998333e-04, 2.44153944e-03, 7.31288068e-04,
        5.15355753e-05, 4.47829887e-04, 1.63917447e-03, 5.90045155e-04,
        1.43875813e-04, 1.43816047e-04, 2.99714956e-04, 1.66198103e-03,
        1.70823969e-04, 6.47142690e-05, 6.01905227e-04, 2.60837335e-05,
        1.71361078e-04, 1.50537272e-04, 2.93134261e-05, 3.05256140e-04]),
 'mean_score_time': array([0.00603571, 0.00563884, 0.00536795, 0.00333099, 0.0043077 ,
        0.00337877, 0.00423508, 0.00340343, 0.00492096, 0.00336676,
        0.00457487, 0.00372233, 0.00429649, 0.00320759, 0.00433006,
        0.00340252, 0.00427856, 0.00347824, 0.00418081, 0.00331454,
        0.00429745, 0.00360794, 0.00427938, 0.00334125, 0.00641751,
        0.00358067, 0.00411716, 0.00339384, 0.00959911, 0.00353274,
        0.00435147, 0.00337496, 0.00428352, 0.00336428, 0.00428963,
        0.00368891, 0.00421548, 0.00378919, 0.00429049, 0.003336  ,
        0.0042769 , 0.00341334, 0.00407243, 0.00330591, 0.00422225,
        0.00331192, 0.00449858, 0.00339293, 0.00402522, 0.00318837,
        0.0042726 , 0.00333672, 0.00413103, 0.0033814 , 0.01842804,
        0.00326433, 0.00416417, 0.00357447, 0.00521646, 0.0032227 ,
        0.00430765, 0.00326786, 0.00459871, 0.00535722, 0.00404296,
        0.0032053 , 0.00408096, 0.00308447, 0.00407143, 0.00317736,
        0.00400634, 0.00381918]),
 'std_score_time': array([2.24189698e-03, 2.95960857e-03, 1.84943708e-03, 1.10360703e-04,
        1.16396273e-04, 1.02751670e-04, 4.96081176e-05, 8.50238227e-05,
        1.14932875e-03, 7.46147923e-05, 2.65884015e-04, 3.78358990e-04,
        7.07929603e-05, 1.85773615e-04, 1.27502511e-04, 1.33328939e-04,
        5.71102034e-05, 7.29908891e-05, 5.66097492e-05, 1.54039836e-04,
        9.64398172e-05, 4.46637750e-04, 3.73674254e-05, 1.69176179e-04,
        2.53847567e-03, 5.56879121e-04, 2.70008535e-04, 1.04066845e-04,
        5.41794686e-03, 1.84618921e-04, 9.88365765e-05, 2.27404366e-04,
        8.80191022e-05, 8.34701232e-05, 9.14231267e-05, 1.93277612e-04,
        2.29325560e-04, 4.69759558e-04, 1.00709611e-04, 5.54656933e-05,
        4.82573811e-05, 2.55322144e-05, 1.99721979e-04, 4.29002417e-05,
        1.85052484e-04, 2.95782823e-05, 7.22095050e-04, 8.72112871e-05,
        7.08405754e-05, 2.22328310e-04, 1.25707389e-04, 4.58543828e-05,
        1.76996622e-04, 6.49844554e-05, 2.12681979e-02, 7.49712672e-05,
        7.58706809e-05, 6.38741316e-04, 1.33499285e-03, 7.98890817e-05,
        4.07781887e-04, 1.42276702e-04, 6.51987253e-04, 1.94856081e-03,
        5.34575926e-05, 7.02531809e-05, 3.86508488e-04, 6.68721232e-05,
        1.36632810e-04, 3.44256614e-05, 4.87110571e-05, 7.12156725e-04]),
 'param_algorithm': masked_array(data=['auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'auto', 'auto', 'auto', 'auto', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_metric': masked_array(data=['minkowski', 'minkowski', 'minkowski', 'minkowski',
                    'minkowski', 'minkowski', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan',
                    'manhattan', 'manhattan', 'minkowski', 'minkowski',
                    'minkowski', 'minkowski', 'minkowski', 'minkowski',
                    'euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'manhattan', 'manhattan',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan',
                    'minkowski', 'minkowski', 'minkowski', 'minkowski',
                    'minkowski', 'minkowski', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan',
                    'manhattan', 'manhattan', 'minkowski', 'minkowski',
                    'minkowski', 'minkowski', 'minkowski', 'minkowski',
                    'euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'manhattan', 'manhattan',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_n_neighbors': masked_array(data=[1, 1, 5, 5, 10, 10, 1, 1, 5, 5, 10, 10, 1, 1, 5, 5, 10,
                    10, 1, 1, 5, 5, 10, 10, 1, 1, 5, 5, 10, 10, 1, 1, 5, 5,
                    10, 10, 1, 1, 5, 5, 10, 10, 1, 1, 5, 5, 10, 10, 1, 1,
                    5, 5, 10, 10, 1, 1, 5, 5, 10, 10, 1, 1, 5, 5, 10, 10,
                    1, 1, 5, 5, 10, 10],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_weights': masked_array(data=['uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'algorithm': 'auto',
   'metric': 'minkowski',
   'n_neighbors': 1,
   'weights': 'uniform'},
  {'algorithm': 'auto',
   'metric': 'minkowski',
   'n_neighbors': 1,
   'weights': 'distance'},
  {'algorithm': 'auto',
   'metric': 'minkowski',
   'n_neighbors': 5,
   'weights': 'uniform'},
  {'algorithm': 'auto',
   'metric': 'minkowski',
   'n_neighbors': 5,
   'weights': 'distance'},
  {'algorithm': 'auto',
   'metric': 'minkowski',
   'n_neighbors': 10,
   'weights': 'uniform'},
  {'algorithm': 'auto',
   'metric': 'minkowski',
   'n_neighbors': 10,
   'weights': 'distance'},
  {'algorithm': 'auto',
   'metric': 'euclidean',
   'n_neighbors': 1,
   'weights': 'uniform'},
  {'algorithm': 'auto',
   'metric': 'euclidean',
   'n_neighbors': 1,
   'weights': 'distance'},
  {'algorithm': 'auto',
   'metric': 'euclidean',
   'n_neighbors': 5,
   'weights': 'uniform'},
  {'algorithm': 'auto',
   'metric': 'euclidean',
   'n_neighbors': 5,
   'weights': 'distance'},
  {'algorithm': 'auto',
   'metric': 'euclidean',
   'n_neighbors': 10,
   'weights': 'uniform'},
  {'algorithm': 'auto',
   'metric': 'euclidean',
   'n_neighbors': 10,
   'weights': 'distance'},
  {'algorithm': 'auto',
   'metric': 'manhattan',
   'n_neighbors': 1,
   'weights': 'uniform'},
  {'algorithm': 'auto',
   'metric': 'manhattan',
   'n_neighbors': 1,
   'weights': 'distance'},
  {'algorithm': 'auto',
   'metric': 'manhattan',
   'n_neighbors': 5,
   'weights': 'uniform'},
  {'algorithm': 'auto',
   'metric': 'manhattan',
   'n_neighbors': 5,
   'weights': 'distance'},
  {'algorithm': 'auto',
   'metric': 'manhattan',
   'n_neighbors': 10,
   'weights': 'uniform'},
  {'algorithm': 'auto',
   'metric': 'manhattan',
   'n_neighbors': 10,
   'weights': 'distance'},
  {'algorithm': 'ball_tree',
   'metric': 'minkowski',
   'n_neighbors': 1,
   'weights': 'uniform'},
  {'algorithm': 'ball_tree',
   'metric': 'minkowski',
   'n_neighbors': 1,
   'weights': 'distance'},
  {'algorithm': 'ball_tree',
   'metric': 'minkowski',
   'n_neighbors': 5,
   'weights': 'uniform'},
  {'algorithm': 'ball_tree',
   'metric': 'minkowski',
   'n_neighbors': 5,
   'weights': 'distance'},
  {'algorithm': 'ball_tree',
   'metric': 'minkowski',
   'n_neighbors': 10,
   'weights': 'uniform'},
  {'algorithm': 'ball_tree',
   'metric': 'minkowski',
   'n_neighbors': 10,
   'weights': 'distance'},
  {'algorithm': 'ball_tree',
   'metric': 'euclidean',
   'n_neighbors': 1,
   'weights': 'uniform'},
  {'algorithm': 'ball_tree',
   'metric': 'euclidean',
   'n_neighbors': 1,
   'weights': 'distance'},
  {'algorithm': 'ball_tree',
   'metric': 'euclidean',
   'n_neighbors': 5,
   'weights': 'uniform'},
  {'algorithm': 'ball_tree',
   'metric': 'euclidean',
   'n_neighbors': 5,
   'weights': 'distance'},
  {'algorithm': 'ball_tree',
   'metric': 'euclidean',
   'n_neighbors': 10,
   'weights': 'uniform'},
  {'algorithm': 'ball_tree',
   'metric': 'euclidean',
   'n_neighbors': 10,
   'weights': 'distance'},
  {'algorithm': 'ball_tree',
   'metric': 'manhattan',
   'n_neighbors': 1,
   'weights': 'uniform'},
  {'algorithm': 'ball_tree',
   'metric': 'manhattan',
   'n_neighbors': 1,
   'weights': 'distance'},
  {'algorithm': 'ball_tree',
   'metric': 'manhattan',
   'n_neighbors': 5,
   'weights': 'uniform'},
  {'algorithm': 'ball_tree',
   'metric': 'manhattan',
   'n_neighbors': 5,
   'weights': 'distance'},
  {'algorithm': 'ball_tree',
   'metric': 'manhattan',
   'n_neighbors': 10,
   'weights': 'uniform'},
  {'algorithm': 'ball_tree',
   'metric': 'manhattan',
   'n_neighbors': 10,
   'weights': 'distance'},
  {'algorithm': 'kd_tree',
   'metric': 'minkowski',
   'n_neighbors': 1,
   'weights': 'uniform'},
  {'algorithm': 'kd_tree',
   'metric': 'minkowski',
   'n_neighbors': 1,
   'weights': 'distance'},
  {'algorithm': 'kd_tree',
   'metric': 'minkowski',
   'n_neighbors': 5,
   'weights': 'uniform'},
  {'algorithm': 'kd_tree',
   'metric': 'minkowski',
   'n_neighbors': 5,
   'weights': 'distance'},
  {'algorithm': 'kd_tree',
   'metric': 'minkowski',
   'n_neighbors': 10,
   'weights': 'uniform'},
  {'algorithm': 'kd_tree',
   'metric': 'minkowski',
   'n_neighbors': 10,
   'weights': 'distance'},
  {'algorithm': 'kd_tree',
   'metric': 'euclidean',
   'n_neighbors': 1,
   'weights': 'uniform'},
  {'algorithm': 'kd_tree',
   'metric': 'euclidean',
   'n_neighbors': 1,
   'weights': 'distance'},
  {'algorithm': 'kd_tree',
   'metric': 'euclidean',
   'n_neighbors': 5,
   'weights': 'uniform'},
  {'algorithm': 'kd_tree',
   'metric': 'euclidean',
   'n_neighbors': 5,
   'weights': 'distance'},
  {'algorithm': 'kd_tree',
   'metric': 'euclidean',
   'n_neighbors': 10,
   'weights': 'uniform'},
  {'algorithm': 'kd_tree',
   'metric': 'euclidean',
   'n_neighbors': 10,
   'weights': 'distance'},
  {'algorithm': 'kd_tree',
   'metric': 'manhattan',
   'n_neighbors': 1,
   'weights': 'uniform'},
  {'algorithm': 'kd_tree',
   'metric': 'manhattan',
   'n_neighbors': 1,
   'weights': 'distance'},
  {'algorithm': 'kd_tree',
   'metric': 'manhattan',
   'n_neighbors': 5,
   'weights': 'uniform'},
  {'algorithm': 'kd_tree',
   'metric': 'manhattan',
   'n_neighbors': 5,
   'weights': 'distance'},
  {'algorithm': 'kd_tree',
   'metric': 'manhattan',
   'n_neighbors': 10,
   'weights': 'uniform'},
  {'algorithm': 'kd_tree',
   'metric': 'manhattan',
   'n_neighbors': 10,
   'weights': 'distance'},
  {'algorithm': 'brute',
   'metric': 'minkowski',
   'n_neighbors': 1,
   'weights': 'uniform'},
  {'algorithm': 'brute',
   'metric': 'minkowski',
   'n_neighbors': 1,
   'weights': 'distance'},
  {'algorithm': 'brute',
   'metric': 'minkowski',
   'n_neighbors': 5,
   'weights': 'uniform'},
  {'algorithm': 'brute',
   'metric': 'minkowski',
   'n_neighbors': 5,
   'weights': 'distance'},
  {'algorithm': 'brute',
   'metric': 'minkowski',
   'n_neighbors': 10,
   'weights': 'uniform'},
  {'algorithm': 'brute',
   'metric': 'minkowski',
   'n_neighbors': 10,
   'weights': 'distance'},
  {'algorithm': 'brute',
   'metric': 'euclidean',
   'n_neighbors': 1,
   'weights': 'uniform'},
  {'algorithm': 'brute',
   'metric': 'euclidean',
   'n_neighbors': 1,
   'weights': 'distance'},
  {'algorithm': 'brute',
   'metric': 'euclidean',
   'n_neighbors': 5,
   'weights': 'uniform'},
  {'algorithm': 'brute',
   'metric': 'euclidean',
   'n_neighbors': 5,
   'weights': 'distance'},
  {'algorithm': 'brute',
   'metric': 'euclidean',
   'n_neighbors': 10,
   'weights': 'uniform'},
  {'algorithm': 'brute',
   'metric': 'euclidean',
   'n_neighbors': 10,
   'weights': 'distance'},
  {'algorithm': 'brute',
   'metric': 'manhattan',
   'n_neighbors': 1,
   'weights': 'uniform'},
  {'algorithm': 'brute',
   'metric': 'manhattan',
   'n_neighbors': 1,
   'weights': 'distance'},
  {'algorithm': 'brute',
   'metric': 'manhattan',
   'n_neighbors': 5,
   'weights': 'uniform'},
  {'algorithm': 'brute',
   'metric': 'manhattan',
   'n_neighbors': 5,
   'weights': 'distance'},
  {'algorithm': 'brute',
   'metric': 'manhattan',
   'n_neighbors': 10,
   'weights': 'uniform'},
  {'algorithm': 'brute',
   'metric': 'manhattan',
   'n_neighbors': 10,
   'weights': 'distance'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667]),
 'split1_test_score': array([0.96666667, 0.96666667, 1.        , 1.        , 1.        ,
        1.        , 0.96666667, 0.96666667, 1.        , 1.        ,
        1.        , 1.        , 0.96666667, 0.96666667, 0.96666667,

In [155]:
result2 = pd.DataFrame(classifier2.cv_results_)
result2

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_metric,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003737,0.000894,0.006036,0.002242,auto,minkowski,1,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,49
1,0.004671,0.001413,0.005639,0.002960,auto,minkowski,1,distance,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,49
2,0.004818,0.003504,0.005368,0.001849,auto,minkowski,5,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,17
3,0.002941,0.000171,0.003331,0.000110,auto,minkowski,5,distance,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,32
4,0.003070,0.000097,0.004308,0.000116,auto,minkowski,10,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.966667,1.000000,1.000000,0.933333,1.0,0.980000,0.026667,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,0.002866,0.000026,0.003084,0.000067,brute,manhattan,1,distance,"{'algorithm': 'brute', 'metric': 'manhattan', ...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,49
68,0.002824,0.000171,0.004071,0.000137,brute,manhattan,5,uniform,"{'algorithm': 'brute', 'metric': 'manhattan', ...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,41
69,0.002797,0.000151,0.003177,0.000034,brute,manhattan,5,distance,"{'algorithm': 'brute', 'metric': 'manhattan', ...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,41
70,0.002870,0.000029,0.004006,0.000049,brute,manhattan,10,uniform,"{'algorithm': 'brute', 'metric': 'manhattan', ...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,17
71,0.003026,0.000305,0.003819,0.000712,brute,manhattan,10,distance,"{'algorithm': 'brute', 'metric': 'manhattan', ...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,32

In [157]:
result2[['param_n_neighbors','param_algorithm','param_metric','param_weights','mean_test_score']]

,param_n_neighbors,param_algorithm,param_metric,param_weights,mean_test_score
0,1,auto,minkowski,uniform,0.960000
1,1,auto,minkowski,distance,0.960000
2,5,auto,minkowski,uniform,0.973333
3,5,auto,minkowski,distance,0.966667
4,10,auto,minkowski,uniform,0.980000
...,...,...,...,...,...
67,1,brute,manhattan,distance,0.960000
68,5,brute,manhattan,uniform,0.960000
69,5,brute,manhattan,distance,0.960000
70,10,brute,manhattan,uniform,0.973333
71,10,brute,manhattan,distance,0.966667