## Pandas Series 
##### A seires is a 1-D labeled array capable of holding any data type. The axis lables are collectively called the index

### Creating Series
#### there are numbers of ways to create a pandas series

In [2]:
import numpy as np
import pandas as pd

In [8]:
labels =  ['a','b','c']
arr = [10,20,30]
d = {1:10,2:20,3:30}

In [4]:
pd.Series(labels)

0    a
1    b
2    c
dtype: str

In [7]:
pd.Series(arr,index=labels)

a    10
b    20
c    30
dtype: int64

In [10]:
pd.Series(d,index = labels)

a   NaN
b   NaN
c   NaN
dtype: float64

In [18]:
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "London", "Paris"]
}

pd.DataFrame(data)

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

In [20]:
#  Create DataFrame from a list of lists
data_list = [
    ["David", 40, "Berlin"],
    ["Eva", 28, "Tokyo"]
]
df2 = pd.DataFrame(data_list)
col = ["Name", "Age", "City"]
df2 = pd.DataFrame(data_list, columns=col)
df2

    Name  Age    City
0  David   40  Berlin
1    Eva   28   Tokyo

In [23]:
df2["City"]

0    Berlin
1     Tokyo
Name: City, dtype: str

##### creating new column

In [25]:
df2["job"]=["Teacher","Manager"]
pd.DataFrame(df2)

    Name  Age    City      job
0  David   40  Berlin  Teacher
1    Eva   28   Tokyo  Manager